Added externally referenced declaration wrapper to reflifc
AndreyG/ifc-reader pull request #23
Opened 2023-05-13 20:03 UTC by FireFlyForLife

2023-05-14 10:57 UTC, AndreyG commented
Thank you for the contribution! It looks really useful and I'm ready to merge it as is, but could you please be so kind to resolve the comment above?

2023-05-14 18:11 UTC, FireFlyForLife commented
Of course! But I don't see any comment above, what was it about?

2023-05-14 18:16 UTC, AndreyG commented
![image](https://github.com/AndreyG/ifc-reader/assets/235190/895fff4c-bad0-4c23-9c9c-f0fcbd144712)

2023-05-14 19:05 UTC, FireFlyForLife commented
Alright! you might need to mark the review as "finished" before I can see the comments.

About the questions specifically. I can see the local_index not being necessary.
About removing the the owner & partition methods and instead returning reflifc::ModuleReference. I'd then expect those 2 methods on the ModuleReference class. Was that your intention too?

2023-05-14 19:16 UTC, AndreyG requested changes

2023-05-14 19:16 UTC, AndreyG commented on lib/reflifc/include/reflifc/decl/DeclarationReference.h
> +        ifc::DeclIndex local_index() const;
Is it really needed to provide access to `local_index`? Isn't `referenced_declaration` enough?

2023-05-14 19:16 UTC, AndreyG commented on lib/reflifc/include/reflifc/decl/DeclarationReference.h
> +        const char* owner() const;
I'd prefer to provide single method returning `reflifc::ModuleReference` (= `ifc::ModuleReference + ifc::File const*`), instead of 2 separate methods `owner()` and `partition()`. Will it work for you?

2023-05-14 19:17 UTC, AndreyG commented
> Alright! you might need to mark the review as "finished" before I can see the comments.

I didn't know this :)

> About the questions specifically. I can see the local_index not being necessary. About removing the the owner & partition methods and instead returning reflifc::ModuleReference. I'd then expect those 2 methods on the ModuleReference class. Was that your intention too?

Exactly, that's my intention.

2023-05-15 21:32 UTC, AndreyG approved these changes

2023-05-15 21:32 UTC, merged